### ISSUE TITLE
MCS fails to handle empty rows of input

### ISSUE THREAD

**Issue by nunezco2** [IN-CORE/pyincore#195]
When a data frame contains empty rows, MCS cannot proceed properly with the computation. Ideally, MCS should detect the empty rows and throw a warning indicating that empty rows have been removed. If the resulting data frame is empty or below some critical number of rows, MCS should halt with an error.

**Comment by nunezco2** [comment]
Decision:

* Investigate the effect of empty rows
* Set to Nan

**Comment by longshuicy** [comment]
This is related to the meandamage as well #131

**Comment by longshuicy** [comment]
First we need to investigate the source of empty rows. One potential cause is there is no proper fragility mapped to that inventory?

**Comment by navarroc** [comment]
This change has introduced a bug. If you run the unit test in main, the output files contain results. If you run the test in develop (with this change), the output has NaN. If you print the "type" in the analysisutil change to float_to_decimal, the type is "str" and it only returns a Decimal IF the type is float.
