### ISSUE TITLE
Refactoring caching mechanism to use multiple repositories

### ISSUE THREAD

**Issue by nunezco2** [IN-CORE/pyincore#196]

**Comment by navarroc** [comment]
For this issue, the goal is to allow someone to allow caching from multiple repositories and keeping the caches separate so it's clear where the data came from. 

Currently, there is a folder .incore/cache_data that stores datasets by ID with no distinction about which repository it came from. For example, if I connect to incore-dev.ncsa and fetch a dataset and then subsequently connect to incore.ncsa and fetch a dataset, both would be stored in cache_data. We need to design a cache folder scheme (maybe something like .incore/<repository-url>).
