### ISSUE TITLE
Create combined building damage from surge-wave, wind and flood and output max damage

### ISSUE THREAD

**Issue by navarroc** [IN-CORE/pyincore#199]
The analysis needs to take 3 building damage inputs - one for surge-wave, one for wind and one from flood and output the maximum damage.

**Comment by navarroc** [comment]
This analysis takes 3 inputs as described previously and does two things:

1. Computes individual max damage state for the 3 inputs using the DataProcessUtil.get_max_damage_state
2. From the individual max damage states, it selects the maximum and assigns it to the building

Output will be:
guid, max_state (incore:maxDamageState)

**Comment by longshuicy** [comment]
code runs and looks good to me. Two things i noticed:

- I saw a deprecated warning
```
/Users/cwang138/Documents/INCORE-2.0/pyincore/pyincore/analyses/combinedwindwavesurgebuildingdamage/combinedwindwavesurgebuildingdamage.py:51: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  max_val = combined_output[max_damage_states].max(axis=1)
```

- i notice the final output only documents the maximum state, not the maximum combined probability? Is that intended?
