### ISSUE TITLE
Clustering should be made more generic so user can specify the column to cluster on

### ISSUE THREAD

**Issue by navarroc** [IN-CORE/pyincore#216]
The assumption is the archetype mapping CSV contains a column called "archetype" and the building dataset also contains a column called archetype so it can cluster the results; however, it would be good if the clustering were more generic so you could specify the column to cluster on (e.g. OCC_TYPE) assuming the user provides clustering by OCC_TYPE.

**Comment by navarroc** [comment]
DataProcessUtil handles the clustering

**Comment by longshuicy** [comment]
This is done.
