### ISSUE TITLE
Use pandas.concat instead of frame.append method

### ISSUE THREAD

**Issue by Vismayak** [IN-CORE/pyincore#220]
In order to tackle this warning which occurs when `.append()` is used-
`/Users/mohanar2/Desktop/NCSA Projects/IN-CORE/pyincore/pyincore/analyses/transportationrecovery/transportationrecovery.py:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append(node['properties'], ignore_index=True)`

We will need to replace the methods with `concat` and also modify the `requirements.txt`, ` setup.py`, or other files to set the pandas minimum version as well.

**Comment by longshuicy** [comment]
This is addressed as a part of the pandas 2.0 upgrade #310
