### ISSUE TITLE
CGE data type does not need to include testbed

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/pyincore#265]
- [x] 1. Keep seaside cge input datasets untouched

- [x] 2. Rename Joplin CGE dataset names without Joplin
i.e.
incore:JoplinCGEsam ==> incore:CGEsam
incore:JoplinCGEbb ==> incore:CGEbb
incore:JoplinCGEiout ==> ...
incore:JoplinCGEmisc
incore:JoplinCGEmisch
incore:JoplinCGElandcap
incore:JoplinCGEemploy
incore:JoplinCGEigtd
incore:JoplinCGEtauff
incore:JoplinCGEjobcr
incore:JoplinCGEoutcr
incore:capitalShocks

- [x] 3. Same with SLC CGE similar way

- [x] 4. Search the incore, incore-dev, incore-tst data collection to replace existing data's dataTypes

- [x] 5. Check incore-docs for places mentioning those input dataset types. e.g. https://github.com/IN-CORE/incore-docs/blob/develop/manual_jb/content/analyses/joplin_cge.md

- [ ] 6. There is no SLC CGE incore-doc yet; when creating it make sure you put the correct dataType https://github.com/IN-CORE/incore-docs/issues/190  
- [x] 7. Update spec in pyincore joplincge and saltlakecge

**Comment by ywkim312** [comment]
tst cluster
01, 5dc1e620b9219c06dd2f473a, JoplinCGEbb
02, 5dc1e6d8b9219c06dd2f475e, JoplinCGEiout
03, 5dc1e736b9219c06dd2f4782, JoplinCGEmisc
04, 5dc1e7b5b9219c06dd2f47a6, JoplinCGEmisch
05, 5dc1e810b9219c06dd2f47ca, JoplinCGElandcap
06, 5dc1e85ab9219c06dd2f47ee, JoplinCGEemploy
07, 5dc1e895b9219c06dd2f4812, JoplinCGEigtd
08, 5dc1e8eeb9219c06dd2f4836, JoplinCGEtauff
09, 5dc1e924b9219c06dd2f485a, JoplinCGEtpc
10, 5dc1e962b9219c06dd2f487e, JoplinCGEjobcr
11, 5dc1e9aeb9219c06dd2f48bc, JoplinCGEoutcr
12, 5dc2049bb9219c06dd2f53b8, JoplinCGE
13, 5dd85ae7b9219c06d4da8de4, JoplinCGEsam
14, 5f17393633b2700c11feab38, Seaside (no change)
15, 5f173a8ec98cf43417c8953b, Seaside (no change)
16, 5f173c97c98cf43417c8955d, Seaside (no change)
17, 5f173d262fab4d660a8e9f9c, Seaside (no change)
18, 5f173d6bc98cf43417c89561, Seaside (no change)
19, 5f174211c98cf43417c89565, Seaside (no change)
20, 603d23d634f29a7fa41c4c4e, Seaside (no change)
21, 630e5f725e639267de334b25, Seaside (no change)
22, 630e5fd388470b319562bbec, Shelby (no change)
23, 630e6013f5438e1f8c51cea9, Shelby (no change)
24, 630e604f88470b319562bbed, Shelby (no change)
25, 630e60a9f5438e1f8c51ceaa, Shelby (no change)
26, 630e60fd88470b319562bbee, Shelby (no change)

**Comment by ywkim312** [comment]
dev cluster
01, 5cdc7b585648c4048fb53062, JoplinCGEsam
02, 5cdc7d295648c4048fb53089, JoplinCGEbb
03, 5cdc7df65648c4048fb530ab, JoplinCGEemploy
04, 5cdc7e405648c4048fb530cd, JoplinCGEigtd
05, 5cdc7e965648c4048fb530ef, JoplinCGEiout
06, 5cdc7ed25648c4048fb5310c, JoplinCGEjobcr
07, 5cdc7f0a5648c4048fb5312e, JoplinCGElandcap
08, 5cdc7f4f5648c4048fb53150, JoplinCGEmisc
09, 5cdc7fa05648c4048fb53172, JoplinCGEmisch
10, 5cdc7fde5648c4048fb53194, JoplinCGEoutcr
11, 5cdc805a5648c4048fb531d8, JoplinCGEtpc
12, 5cdc81da5648c4048fb532b7, JoplinCGEtauff
13, 5f6127105060967d84ab0f99, Seaside (no change)
14, 5f61278f5060967d84ab0fc2, Seaside (no change)
15, 5f6127e85060967d84ab0feb, Seaside (no change)
16, 5f61284d5060967d84ab1014, Seaside (no change)
17, 5f6128b85060967d84ab103d, Seaside (no change)
18, 5f6129035060967d84ab1066, Seaside (no change)
19, 5f6132ad5060967d84abdfd3, Seaside (no change)
20, 6138f39fca423a005e42232a, JoplinCGEsam
21, 6138f3faca423a005e4223bc, JoplinCGEbb
22, 6138f427ca423a005e42244e, JoplinCGEiout
23, 6138f452ca423a005e4224e0, JoplinCGEmisc
24, 6138fda7ca423a005e422574, JoplinCGEmisch
25, 6138fdcfca423a005e422606, JoplinCGElandcap
26, 6138fe38ca423a005e422698, JoplinCGEemploy
27, 6138fe68ca423a005e42272a, JoplinCGEigtd
28, 6138fe99ca423a005e4227bc, JoplinCGEtauff
29, 6138fecbca423a005e42284e, JoplinCGEjobcr
30, 6138fef6ca423a005e4228e0, JoplinCGEoutcr
31, 630e5906c8f8b7614f6e5c6d, ShelbyCGEsam
32, 630e5ac3c8f8b7614f6e5c76, ShelbyCGEbb
33, 630e5ba5c8f8b7614f6e5c7e, ShelbyCGEemploy
34, 630e5c59c8f8b7614f6e5c86, ShelbyCGEjobcr
35, 630e5d08c8f8b7614f6e5c8e, ShelbyCGEhhtable
36, 630e5e0bc8f8b7614f6e5c96, ShelbyCGEsim
37, 63a354f54b8432383268cd92, JoplinCGEbb
38, 63a357ec4b8432383268ceda, JoplinCGEoutcr
39, 63c836d94b843238326bd982, JoplinCGEemploy
40, 63c837f74b843238326be507, JoplinCGEjobcr
41, 63c838414b843238326be50d, JoplinCGEoutcr
42, 63c838954b843238326be513, JoplinCGEmisch
43, 63c8398f4b843238326be519, JoplinCGEsam

**Comment by ywkim312** [comment]
prod 
01, 5dc1e620b9219c06dd2f473a, JoplinCGEbb
02, 5dc1e6d8b9219c06dd2f475e, JoplinCGEiout
03, 5dc1e736b9219c06dd2f4782, JoplinCGEmisc
04, 5dc1e7b5b9219c06dd2f47a6, JoplinCGEmisch
05, 5dc1e810b9219c06dd2f47ca, JoplinCGElandcap
06, 5dc1e85ab9219c06dd2f47ee, JoplinCGEemploy
07, 5dc1e895b9219c06dd2f4812, JoplinCGEigtd
08, 5dc1e8eeb9219c06dd2f4836, JoplinCGEtauff
09, 5dc1e924b9219c06dd2f485a, JoplinCGEtpc
10, 5dc1e962b9219c06dd2f487e, JoplinCGEjobcr
11, 5dc1e9aeb9219c06dd2f48bc, JoplinCGEoutcr
12, 5dc2049bb9219c06dd2f53b8, JoplinCGE
13, 5dd85ae7b9219c06d4da8de4, JoplinCGEsam
14, 5f17393633b2700c11feab38, Seaside (no change)
15, 5f173a8ec98cf43417c8953b, Seaside (no change)
16, 5f173c97c98cf43417c8955d, Seaside (no change)
17, 5f173d262fab4d660a8e9f9c, Seaside (no change)
18, 5f173d6bc98cf43417c89561, Seaside (no change)
19, 5f174211c98cf43417c89565, Seaside (no change)
20, 603d23d634f29a7fa41c4c4e, Seaside (no change)
21, 630e5f725e639267de334b25, ShelbyCGEsam
22, 630e5fd388470b319562bbec, ShelbyCGEbb
23, 630e6013f5438e1f8c51cea9, ShelbyCGEemploy
24, 630e604f88470b319562bbed, ShelbyCGEjobcr
25, 630e60a9f5438e1f8c51ceaa, ShelbyCGEhhtable
26, 630e60fd88470b319562bbee, ShelbyCGEsim
27, 63daaf5ca011a9746c954081, JoplinCGEbb
28, 63daafa9c4b5713b9c0c96ae, JoplinCGEsam
29, 63daafe5a011a9746c954082, JoplinCGEmisch
30, 63dab018c4b5713b9c0c96af, JoplinCGEemploy
31, 63dab074a011a9746c954083, JoplinCGEjobcr
32, 63dab0a7c4b5713b9c0c96b0, JoplinCGEoutcr

**Comment by longshuicy** [comment]
Thanks for the detailed documentations!
I will do the pyincore spec change and link the PR here
