### ISSUE TITLE
HUA dataset has wrong blockid

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/pyincore#305]
```
File ~/opt/miniconda3/envs/incoreRC1.9.0/lib/python3.8/site-packages/pandas/core/dtypes/astype.py:230, in astype_array(values, dtype, copy)
    227     values = values.astype(dtype, copy=copy)
    229 else:
--> 230     values = astype_nansafe(values, dtype, copy=copy)
    232 # in pandas we don't store numpy str dtypes, so convert to object
    233 if isinstance(dtype, np.dtype) and issubclass(values.dtype.type, str):

File ~/opt/miniconda3/envs/incoreRC1.9.0/lib/python3.8/site-packages/pandas/core/dtypes/astype.py:170, in astype_nansafe(arr, dtype, copy, skipna)
    166     raise ValueError(msg)
    168 if copy or is_object_dtype(arr.dtype) or is_object_dtype(dtype):
    169     # Explicit copy, or required since NumPy can't view from / to object.
--> 170     return arr.astype(dtype, copy=True)
    172 return arr.astype(dtype, copy=copy)

ValueError: invalid literal for int() with base 10: '482000000000000.0'
``` 

Detail run this notebook:
https://github.com/IN-CORE/incore-docs/blob/2a2b7bc99bf0000d7b35a4a9ba7838b7f88b3248/notebooks/galveston_community_app.ipynb

**Comment by longshuicy** [comment]
It is because HUA dataset we use is wrong which trickle down to population dislocation and later HHRS
HUA ID `63ff8e895367c2261b4cb2ef`

check the block Id column


![Image](https://user-images.githubusercontent.com/13950475/227822614-6a5902d4-e448-466f-9186-1ad970c4d694.png)

It should have real value as integer


![Image](https://user-images.githubusercontent.com/13950475/227822646-523c7fa1-9eb1-43e7-8462-a8c6f849a447.png)

**Comment by ywkim312** [comment]
dataset has been fixed. @longshuicy Please check it out

**Comment by ywkim312** [comment]
notebook ran successfully until the end in incore-lab
