### ISSUE TITLE
Seaside & Joplin cge uses a fixed location for temporary files

### ISSUE THREAD

**Issue by navarroc** [IN-CORE/pyincore#312]
Joplin CGE writes a temporary files with the same name to the /tmp folder of the machine running the code; however, this space is not unique in a multi-run scenario. The other CGE implementations (Galveston and Salt Lake) use the current working folder for the temporary files it creates and Joplin should be updated to use the same.

**Comment by jonglee1** [comment]
Seaside CGE has same problem

**Comment by longshuicy** [comment]
addressed
