### ISSUE TITLE
Run pyincore with python 3.8, 3.9, 3.10, and 3.11

### ISSUE THREAD

**Issue by ylyangtw** [IN-CORE/pyincore#330]
For testing. We would like to know which version works or not.

**Comment by robkooper** [comment]
I think we can make this a matrix build and use the python version https://github.com/IN-CORE/pyincore/blob/develop/.github/workflows/pytests.yml#L40

here is an example of a matrix build: https://github.com/IN-CORE/pyincore/blob/develop/.github/workflows/pytests.yml#L40

**Comment by ylyangtw** [comment]
python 3.8 & 3.9 pass the unit tests.
python 3.10 & 3.11 have conflicts with the dependencies in environment.yml.
