### ISSUE TITLE
Intermodal Model Implementation

### ISSUE THREAD

**Issue by ylyangtw** [IN-CORE/pyincore#334]
Visu and I had the first meeting with Anibal and Raul on 5/10. Waiting for their google form submission. Need to review/implement their finished functions after we receive the submission.

**Comment by jonglee1** [comment]
We need to divide the analysis into multiple analysis.

**Comment by ylyangtw** [comment]
For now, Visu will work on bridges (railways) and Ya-Lan will do bridges (roadways)

**Comment by ylyangtw** [comment]
Close this issue as we have created 2 subtasks for it https://github.com/IN-CORE/pyincore/issues/340 https://github.com/IN-CORE/pyincore/issues/341
