### ISSUE TITLE
Refactor building damage analysis to support multiple hazards

### ISSUE THREAD

**Issue by navarroc** [IN-CORE/pyincore#337]
Based on the outcome of #336, refactor building damage analysis implementation to support multiple hazards required by multi-hazard fragilities

**Comment by longshuicy** [comment]
steps:

1. change the building damage input params:
hazard_type: `earthquake+tsunami`
hazard_id: `id1+id2`

2. when reading parameters split by "+" sign. Now we'll have hazard_types as a list and hazard_ids as a list

3. calling both hazard endpoints by add a for loop wrap around [line 133](https://github.com/IN-CORE/pyincore/blob/develop/pyincore/analyses/buildingdamage/buildingdamage.py#L133) to [line 182](https://github.com/IN-CORE/pyincore/blob/develop/pyincore/analyses/buildingdamage/buildingdamage.py#L182) and store the return hazard value approporiate

4. Merging and massaging both of the hazard values to the `hval_dict`. It should look like 
```
{"zero_point_four_sa":number, "Mmax": number}
```

The rest should stay the same.
