### ISSUE TITLE
Contact Omar to figure out why there are buildings with Archetype 0 in the Lumberton Flood Data

### ISSUE THREAD

**Issue by Vismayak** [IN-CORE/pyincore#364]
@longshuicy will CC @Vismayak in the first email

**Comment by longshuicy** [comment]
email sent. Good luck

**Comment by Vismayak** [comment]
<img width="741" alt="image" src="https://github.com/IN-CORE/pyincore/assets/16596733/eaac6d0c-2983-444f-8d38-8322c6a875c1">
