### ISSUE TITLE
Nonstructural building damage hazard exposure column name is too long

### ISSUE THREAD

**Issue by navarroc** [IN-CORE/pyincore#393]
hazard_exposure_as is used to indicated acceleration sensitive hazard exposure and hazard_exposure_ds is used to indicate drift sensitive hazard exposure; however, these names need to be shortened since the DBF can only have 10 characters. 

This issue also causes a bug in the analysisutil.dmg_string_dict_to_dmg_float_dict since it only ignores haz_expose and guid. Whatever we determine the new column names should be will need to be added to the analysisutil to exclude them when determining if a string should be converted to float.

**Comment by navarroc** [comment]
Another option would be to check if hazard_expose_as is yes and hazard_expose_ds is yes, then just make a column haz_expose as yes or partial or no depending on the values. Then analysis util can remain unchanged.

**Comment by longshuicy** [comment]
#390 linking this bug report. That's the second issue you listed
