### ISSUE TITLE
 500 Server Error: Internal Server Error for url

### ISSUE THREAD

**Issue by waqasiqbal123** [IN-CORE/pyincore#413]
Hi All, 

I am trying to upload the bridge inventory dataset to the already created dataset id but it is giving me this error. 

Following is what i am trying to do: 

dataset_metadata = {
    "title":"Delaware Bridges",
    "description": "NBI Data",
    "dataType": "ergo:buildingInventoryVer7",
    "format": "shapefile"
}
created_dataset=data_services.create_dataset(dataset_metadata)
dataset_id=created_dataset['id']
print('dataset is created with id ' + dataset_id)
# %%
files=['C:\\Users\\waqas\\My Drive\\Bridges.shx']
full_dataset = data_services.add_files_to_dataset(dataset_id, files)
print(full_dataset)

Please let me know how can i solve this problem. 

Thanks 
Waqas

**Comment by longshuicy** [comment]
> Hi All,
> 
> I am trying to upload the bridge inventory dataset to the already created dataset id but it is giving me this error.
> 
> Following is what i am trying to do:
> 
> dataset_metadata = { "title":"Delaware Bridges", "description": "NBI Data", "dataType": "ergo:buildingInventoryVer7", "format": "shapefile" } created_dataset=data_services.create_dataset(dataset_metadata) dataset_id=created_dataset['id'] print('dataset is created with id ' + dataset_id)
> 
> # %%
> files=['C:\Users\waqas\My Drive\Bridges.shx'] full_dataset = data_services.add_files_to_dataset(dataset_id, files) print(full_dataset)
> 
> Please let me know how can i solve this problem.
> 
> Thanks Waqas

Hi [waqasiqbal123](https://github.com/waqasiqbal123) Thank you for your question. In order to upload shapefile to our services, you either need to provide all the needed files, e.g. *.shp, *.dbf, *.prj and *.shx. 
In your example, you seems to only included the .shx; with that alone, our system cannot process. 

If you still have problems, you are welcome to use our incore slack channel to ask question or email our [mailing list](incore-dev@lists.illinois.edu). The github right now is mainly for tracking our development internally. Thank you!

**Comment by waqasiqbal123** [comment]
Hi Thanks,

I am searching for the slack group of incore but cannot find it. And also I
have tried to include all 4 files but still it is giving me an error that
GUID is not present.

Thanks
WaqS

**Comment by longshuicy** [comment]
Hi @waqasiqbal123,

Yes all the shapefile needs to have a `GUID` field which we use to identify and differentiate each inventory item (bridge). To add `GUID`, we provide a python method for that, detail please consult this notebook:
https://incore.ncsa.illinois.edu/doc/incore/workshops/20220131/session3/session3-building_damage_analysis.html#step-2-add-guid

Also, here is an invitation to the slack channel https://join.slack.com/t/in-core/shared_invite/zt-24fi2u8sg-KvBLuHuMnAQuumbwnb7hoA

Thanks!

**Comment by waqasiqbal123** [comment]
Thanks , I appreciate that.
