### ISSUE TITLE
Implement Core CGE ML class

### ISSUE THREAD

**Issue by Rashmil-1999** [IN-CORE/pyincore#468]
To limit the need for a user to specify inputs to the CGE-ML analysis, we will build a base class which will be the 'core-cge-ml'. This core class will have the following Inputs and outputs:

Inputs:
- Base Capital values of the sectors.
- Capital Shocks
- Model coefficients for each factor (4 for MMSA)
- Base Factor aggregates for each factor in consideration. (4 for MMSA)

Outputs:
- CSV file for each factor in consideration as per the required format.

The wrapper class for each analysis will take care of feeding the core-cge-ml with:

- Base Capital values of the sectors.
- Model coefficients for each factor (4 for MMSA)
- Base Factor aggregates for each factor in consideration. (4 for MMSA)
- Names of output files from the spec definition

**Comment by longshuicy** [comment]
Addressed.
