### ISSUE TITLE
Add hazardDatasets to Tornado and Earthquake model

### ISSUE THREAD

**Issue by ylyangtw** [IN-CORE/pyincore#474]
After Tornado and Earthquake classes have been updated in incore-services[#213](https://github.com/IN-CORE/incore-services/issues/213), Tornado and Earthquake models in pyincore should be updated accordingly

There are two tasks for this issue:
- Add hazardDatasets to Tornado
- For model Earthquake, change rasterDatasets to hazardDatasets

**Comment by longshuicy** [comment]
@ylyangtw while I was fixing the pytest I actually fixed the tornado and eq. It's quick enough, hope it's ok.

**Comment by ylyangtw** [comment]
> @ylyangtw while I was fixing the pytest I actually fixed the tornado and eq. It's quick enough, hope it's ok.

Wow that's sweet. thanks much Chen!
