### ISSUE TITLE
Black formatter and GH action check

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/pyincore#482]
Maybe it's time we start to look into black formatter in the next release? https://black.readthedocs.io/en/stable/
Here is an clowder example of using black and github action to check that https://github.com/clowder-framework/clowder2/blob/main/.github/workflows/black.yml
_Originally posted by @navarroc in https://github.com/IN-CORE/pyincore/issues/476#issuecomment-1912431477_

**Comment by navarroc** [comment]
We can use pyincore-incubator as an example for setting up black and flake8. If needed, we could make this task just three things:

1. Setting up black/flake8 (pyincore-incubator has a configuration from clowder, maybe that's good enough to borrow directly)
2. Formatting/linting our code with black/flake8 and committing those changes
3. Setting up the pre-commit hook and providing instructions on how to set that up

Later, we could add the github action piece if that makes sense to separate these out.

**Comment by ylyangtw** [comment]
to do: also write down steps for installing pre-commit

**Comment by navarroc** [comment]
You can probably start from pyincore incubator which has some of this.
