### ISSUE TITLE
Investigate in building damage performance issue

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/pyincore#493]
SLC right now takes ~9 min with 8 cpus to finish
With retrofit that's close to ~14 min

Looking into places we can optimize

e.g.. 
I noticed that when we do 
```
fragility_sets = self.fragilitysvc.match_inventory(self.get_input_dataset("dfr3_mapping_set"), buildings, fragility_key)
```
Internally we are looping through all the buildings and find the match and group them to send back

Then we are looping again 
```
 for b in buildings:
                bldg_id = b["id"]
                if bldg_id in fragility_sets:
                ...
```

Could we see if we can calculate the damage on the spot?

**Comment by navarroc** [comment]
From preliminary investigation, using SLC all buildings and 4 cpus on my machine, the building damage takes about 6.5 minutes to finish. Of that time, it spends just over 5 minutes in the fragility matching, about 15s requesting the hazard, about the same amount of time breaking up the data for the threads to work on (15s). The rest is some write time and computing the damage (I didn't break that out). 

Adding in liquefaction adds about 1 min and 30 seconds to the run time so hazard time is about 1 minute 45 seconds.So the most time spent is in fragility matching (5 minutes) and the hazard (almost 2 minutes). The most inefficient part looks to be the fragility matching.

**Comment by longshuicy** [comment]
I'm closing this issue since the initial investigations are finished by @navarroc. Finds are documented above ^
A new issuse will be used for how to optimize based on findings.
