### ISSUE TITLE
Build and deploy datawolf docker image of pyincore 1.17.0

### ISSUE THREAD

**Issue by navarroc** [IN-CORE/pyincore#507]
The latest docker image that we use for executing pyincore with the kubernetes executor is running pyincore 1.10.0. This needs to be built with the latest pyincore (1.17.0)

**Comment by navarroc** [comment]
Latest image is deployed and being tested.

**Comment by longshuicy** [comment]
Thanks so much for catching this! May I close this issue?

**Comment by navarroc** [comment]
> Thanks so much for catching this! May I close this issue?

If all analyses are working, yes. I left it open until I heard back from you on any other testing.

**Comment by longshuicy** [comment]
Galveston & SLC seems to work as expected. Closing this issue :-)
