### ISSUE TITLE
Cluster function does not return expected keys with 0 values in that damage states

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/pyincore#515]
When no building fall into the damage state category, the function fails to return the expected keys for states that have a count of 0. Causing the damage table and compare damage table to break. 

Fix it in https://github.com/IN-CORE/pyincore/blob/3c2eca45a99aab0e446e19061aa86cbf249e2ed9/pyincore/utils/dataprocessutil.py#L174

![Image](https://github.com/IN-CORE/pyincore/assets/13950475/e8aadc42-0575-4204-819a-8b4d1a400772)
e.g. Take a look at the payload of this screenshot; note there is only insiginificant; there should be all 4 states with moderate: 0, extensive:0, complete:0

**Comment by Vismayak** [comment]
Tackled in playbook [issue](https://github.com/IN-CORE/incore-playbook/issues/373). Closing
