### ISSUE TITLE
MLEnabledCgeSlc module documentation is missing

### ISSUE THREAD

**Issue by navarroc** [IN-CORE/pyincore#542]
The MLEnabledCgeSlc needs to be added to modules.rst under the pyincore docs folder here:

https://github.com/IN-CORE/pyincore/tree/develop/docs/source

The documentation from modules.rst is used to build this: https://incore.ncsa.illinois.edu/doc/pyincore/modules.html

**Comment by Rashmil-1999** [comment]
I think we should also add the CoreCGEML... since the Cohort would need it if they ever implement the ML CGE in the future.

**Comment by navarroc** [comment]
Yes, it really should be both core and the SLC model.
