### ISSUE TITLE
convert hua and pd outputs to json

### ISSUE THREAD

**Issue by diegoac2** [IN-CORE/pyincore#9]
Lisa's notebook does not run pyincore analysis. There is a csv file with retrofits Wangoutput_2020-05-28_sheet1.csv which is merged with IN-CORE_2ev3_SetupJoplin_FourInventories_2019-08-06_HUinventory.csv. There are two lines named Population dislocation which is compared to HUA dislocation. That might be the only code to be run in pyIncore.

**Comment by npr99** [comment]
Hi Diego - I am responsible for the IN-CORE_2ev3_SetupJoplin_FourInventories_2019-08-06_HUinventory.csv files.

I am not familiar with the specific notebook from Lisa. Is it the same one that is online? https://incore.ncsa.illinois.edu/doc/incore/notebooks/Joplin_testbed/Joplin_testbed.html#6.-Sociological-Analysis

**Comment by npr99** [comment]
The published Joplin Notebook can be updated with the notebook on my Github Page https://github.com/npr99/IN-CORE_notebooks/blob/main/IN_CORE_CommunityDescription_Joplin.ipynb 

My notebook uses the same building inventory as Lisa's but adds the housing unit inventory and the housing unit allocation method to produce the population data

**Comment by longshuicy** [comment]
Is this task for the playbook? if so i think @ncsa-mo has already figured out how to generate the json. Could you confirm?

**Comment by diegoac2** [comment]
I just moved this from a task in bitbucket. @ncsa-mo can you please look at the questions above?

**Comment by ncsa-mo** [comment]
This task is for the Playbook. It is assigned to me, we have everything to generate a json outputs.

**Comment by longshuicy** [comment]
@ncsa-mo  here is the additional json (Github doesn't allow me to attach json so i turn it to txt, but it should be a json)
[HUA_by_housing_type.txt](https://github.com/IN-CORE/pyincore/files/7211794/HUA_by_housing_type.txt)

There might be one more coming in the future "by_disability", but I haven't got instruction on how to generate this table
