### ISSUE TITLE
add github action to publish to conda

### ISSUE THREAD

**Issue by diegoac2** [IN-CORE/pyincore#93]
We need to automatize publishing our builds to Anaconda.

**Comment by navarroc** [comment]
We need the same thing for pyincore-viz and I created an issue already there. This would be a good one to work on with @robkooper since we want two things:
1. Publish conda builds for releases automatically
2. Publish conda RC builds automatically

**Comment by ywkim312** [comment]
@diegoac2 I will reopen this and assign it to me.

**Comment by ywkim312** [comment]
implemented
